USE [mySpaceman_datdb]
GO

/****** Object:  Table [dbo].[ACN_PLANOGRAMS]    Script Date: 2017-09-07 08:21:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACN_PLANOGRAMS](
	[PLN_ID] [int] NOT NULL,
	[ACCESSEDBY] [nvarchar](255) NULL,
	[ACCESSEDDATE] [datetime] NULL,
	[CREATIONDATE] [datetime] NULL,
	[INUSEBY] [nvarchar](255) NULL,
	[MODIFIEDBY] [nvarchar](255) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[PLANOGRAM] [nvarchar](255) NULL,
	[STATUS] [nvarchar](255) NULL,
	[WERSJA_PLANOGRAMU] [nvarchar](255) NULL,
	[DATA_START] [nvarchar](255) NULL,
	[DATA_STOP] [nvarchar](255) NULL,
	[OWNER] [nvarchar](255) NULL,
 CONSTRAINT [PK_ACN_PLANOGRAMS] PRIMARY KEY CLUSTERED 
(
	[PLN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


